//! Web API runtime integration.

use boa_engine::{Context, JsError, Source};
use slate_dispatcher::OwnedWebCall;

use crate::bindings::WebApiBindings;
use crate::WebApiError;

/// Web API runtime with JavaScript execution.
pub struct WebApiRuntime {
    ctx: Context,
    bindings: WebApiBindings,
}

impl WebApiRuntime {
    /// Create new Web API runtime.
    pub fn new() -> Result<Self, WebApiError> {
        let mut ctx = Context::default();
        let bindings = WebApiBindings::new();

        bindings
            .install(&mut ctx)
            .map_err(|e| WebApiError::JsError(format!("{:?}", e)))?;

        Ok(Self { ctx, bindings })
    }

    /// Evaluate JavaScript code.
    pub fn eval(&mut self, code: &str) -> Result<(), WebApiError> {
        self.ctx
            .eval(Source::from_bytes(code.as_bytes()))
            .map(|_| ())
            .map_err(|e: JsError| WebApiError::JsError(format!("{:?}", e)))
    }

    /// Take all pending WebCalls generated by JavaScript execution.
    pub fn drain_web_calls(&mut self) -> Vec<OwnedWebCall> {
        self.bindings.take_web_calls()
    }

    /// Reset the runtime state (for page navigation).
    pub fn reset(&mut self) {
        // Clear any pending calls
        self.bindings.take_web_calls();
    }
}

impl Default for WebApiRuntime {
    fn default() -> Self {
        Self::new().expect("Failed to create Web API runtime")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_create_runtime() {
        let runtime = WebApiRuntime::new();
        assert!(runtime.is_ok());
    }

    #[test]
    fn test_eval_simple_js() {
        let mut runtime = WebApiRuntime::new().unwrap();
        let result = runtime.eval("1 + 1");
        assert!(result.is_ok());
    }

    #[test]
    fn test_console_log() {
        let mut runtime = WebApiRuntime::new().unwrap();
        let result = runtime.eval("console.log('Hello, Slate!')");
        assert!(result.is_ok());
    }

    #[test]
    fn test_dom_operations() {
        let mut runtime = WebApiRuntime::new().unwrap();
        
        runtime.eval(r#"
            const div = document.createElement('div');
            div.setAttribute('id', 'test');
            const text = document.createTextNode('Hello');
            div.appendChild(text);
        "#).unwrap();

        let calls = runtime.drain_web_calls();
        assert!(calls.len() > 0);
    }

    #[test]
    fn test_storage_api() {
        let mut runtime = WebApiRuntime::new().unwrap();
        
        runtime.eval(r#"
            localStorage.setItem('key', 'value');
            const value = localStorage.getItem('key');
            console.log('Stored value:', value);
        "#).unwrap();
    }

    #[test]
    fn test_performance_api() {
        let mut runtime = WebApiRuntime::new().unwrap();
        
        runtime.eval(r#"
            const start = performance.now();
            console.log('Performance now:', start);
        "#).unwrap();
    }
}
